In [1]:
import numpy as np
from random import randint #creates random integers e.g. randint(1,10)

In [ ]:
#Numpy docs say to use arrays instead of the matrix function
#multidimensional array
matrix_3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([1,1,1])

In [18]:
#can do matrix multiplication with matmul
#docs: https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html
np.matmul(matrix_3x3,vector)

In [146]:
#create list of lists first, then convert to array at the end
def create_rand_matrix(num_rows,num_cols):
    lol = list()
    for i in range(num_rows):
        row_vals = list()
        for j in range(num_cols):
            row_vals.append(randint(1,10))
        lol.append(row_vals)
    matrix = np.array(lol)
    return matrix

In [152]:
create_rand_matrix(2,6)

array([[ 4,  1,  7,  1,  2,  4],
       [ 8,  3,  2,  2,  7, 10]])

In [158]:
matrix1 = create_rand_matrix(3,2)
matrix2 = create_rand_matrix(2,1)
print(matrix1)
print(matrix2)

[[9 9]
 [2 9]
 [1 5]]
[[7]
 [9]]


In [163]:
#by hand
print((9*7) + (9*9))
print((7*2) + (9*9))
print((7*1) + (9*5))

144
95
52


In [164]:
np.matmul(matrix1,matrix2)

array([[144],
       [ 95],
       [ 52]])

In [173]:
course1 = np.array([[1,3,2],[4,0,1]])
course2 = np.array([[1,3],[0,1],[5,2]])
print(course1)
print(course2)

[[1 3 2]
 [4 0 1]]
[[1 3]
 [0 1]
 [5 2]]


In [174]:
np.matmul(course1,course2)

array([[11, 10],
       [ 9, 14]])

In [175]:
course3 = np.array([[1,3],[2,5]])
course4 = np.array([[0,1],[3,2]])
print(course3)
print(course4)

[[1 3]
 [2 5]]
[[0 1]
 [3 2]]


In [176]:
np.matmul(course3,course4)

array([[ 9,  7],
       [15, 12]])

In [ ]:
#Create empty arrays
np.zeros(shape=(3,1))
np.empty(shape=(4,3))